### PR TITLE
Bugfix in deserializer when processing enum type 

### PR DESCRIPTION
**Pull request by AsCat**
**Fixed a bug when isito yaml contains enum type.** 
For example when adding loadBalancer in destination-rule.yaml config file, it will throw exception as there is no default constructor with enum type(default is String type);

I also fixed the tests and yaml template adding enum type.
Can anyone verify this PR?

### CODE REVIEW

**Comment by geoand** [comment]
Thanks @AsCat!

Looks good to me, but I would like @metacosm to approve as well

**Comment by arief-hidayat** [comment]
I would love to have this available in 1.0.1.
Thanks

**Comment by metacosm** [comment]
Going to check today.

**Comment by metacosm** [comment]
Thanks a lot!

**Pull request merged**
