### PR TITLE
Add "Spec" suffix to CRD classes.

### PR DESCRIPTION
**Pull request by metacosm**
UNTESTED!

### CODE REVIEW

**Comment by geoand** [comment]
Should we perhaps create more ITs for the purpose of testing this refactoring?

**Comment by metacosm** [comment]
We can always create more tests… :)

**Comment by geoand** [comment]
Do we have any suspicions of which resources my need more attention due to the refactoring or just because they are suspicious in general?

**Comment by metacosm** [comment]
Not any in particular… ideally, we'd cover everything but the issue there is that each time the API changes, the tests need to be updated which is less than ideal because you're basically left without the safety net during the refactoring… :( Ideally, we'd devise a way to test things end to end without relying so much on the API…

**Comment by geoand** [comment]
That is indeed a concern, but if we don't use the API in the tests we can't really test things end-to-end.
Plus I would add that the integration tests also act as example use cases

**Comment by metacosm** [comment]
Indeed, testing likely user use cases would be great.

**Comment by geoand** [comment]
I will go over the istio boosters and add use cases that we have there, but other than that, I'm not really sure what the most common use cases are :P

I guess we could also take a look at the examples Istio has

**Pull request merged**
