### PR TITLE
Debugging on why shared informers using Istio resources won't work to…

### PR DESCRIPTION
**Pull request by FWiesner**
… fix snowdrop#129

### CODE REVIEW

**Comment by FWiesner** [comment]
@metacosm please check whether my added commit is needed or can be discarded. There seems to be introspection on whether the types implement `Namespaced`, so I've added it before you did your commit

**Comment by FWiesner** [comment]
I'm reverting my commit. Sharded informers work now even without my commit

**Comment by FWiesner** [comment]
My service that uses your library is now coming up as expected and the shared informer is properly working. I got a 404 before when the Controller tried accessing resources as non-namespaced ones and that made the controller thread die silently

**Comment by metacosm** [comment]
I will probably need to spend some time cleaning things up at some point since a lot of what is done here is redundant with what the fabric8 client does. However, it will have to wait for when I have more time (and also want to get more fixes in the client first, in particular moving `CustomResource` outside of the client module and into the package). 

If you are satisfied with this fix, please make the PR ready for review. If you have time, it'd be great if you could rebase the commits so that you remove the `Namespaced` related commits. Thank you for your work! Much appreciated.

**Comment by FWiesner** [comment]
doing the squashing now - I just din't want to rewrite the history while you're potentially in the middle of something

**Comment by FWiesner** [comment]
ready for merge

**Review by metacosm — APPROVED** [review]
Thank you!

**Pull request merged**
